/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MyRegistrationsRouteImport } from './routes/my-registrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterSlugRouteImport } from './routes/register.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminEventsSlugRouteImport } from './routes/admin.events.$slug'
import { Route as AdminCoursesSlugRouteImport } from './routes/admin.courses.$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRegistrationsRoute = MyRegistrationsRouteImport.update({
  id: '/my-registrations',
  path: '/my-registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterSlugRoute = RegisterSlugRouteImport.update({
  id: '/register/$slug',
  path: '/register/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsSlugRoute = AdminEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminCoursesSlugRoute = AdminCoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/courses': typeof CoursesRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-registrations': typeof MyRegistrationsRoute
  '/signup': typeof SignupRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/participants': typeof AdminParticipantsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugRoute
  '/admin/events/$slug': typeof AdminEventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/courses': typeof CoursesRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-registrations': typeof MyRegistrationsRoute
  '/signup': typeof SignupRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/participants': typeof AdminParticipantsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugRoute
  '/admin/events/$slug': typeof AdminEventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/courses': typeof CoursesRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-registrations': typeof MyRegistrationsRoute
  '/signup': typeof SignupRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/participants': typeof AdminParticipantsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugRoute
  '/admin/events/$slug': typeof AdminEventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/courses'
    | '/events'
    | '/login'
    | '/my-registrations'
    | '/signup'
    | '/testimonials'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/participants'
    | '/courses/$slug'
    | '/events/$slug'
    | '/register/$slug'
    | '/admin/'
    | '/admin/courses/$slug'
    | '/admin/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/courses'
    | '/events'
    | '/login'
    | '/my-registrations'
    | '/signup'
    | '/testimonials'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/participants'
    | '/courses/$slug'
    | '/events/$slug'
    | '/register/$slug'
    | '/admin'
    | '/admin/courses/$slug'
    | '/admin/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/courses'
    | '/events'
    | '/login'
    | '/my-registrations'
    | '/signup'
    | '/testimonials'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/participants'
    | '/courses/$slug'
    | '/events/$slug'
    | '/register/$slug'
    | '/admin/'
    | '/admin/courses/$slug'
    | '/admin/events/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyRegistrationsRoute: typeof MyRegistrationsRoute
  SignupRoute: typeof SignupRoute
  TestimonialsRoute: typeof TestimonialsRoute
  RegisterSlugRoute: typeof RegisterSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-registrations': {
      id: '/my-registrations'
      path: '/my-registrations'
      fullPath: '/my-registrations'
      preLoaderRoute: typeof MyRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/$slug': {
      id: '/register/$slug'
      path: '/register/$slug'
      fullPath: '/register/$slug'
      preLoaderRoute: typeof RegisterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$slug': {
      id: '/admin/events/$slug'
      path: '/$slug'
      fullPath: '/admin/events/$slug'
      preLoaderRoute: typeof AdminEventsSlugRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/courses/$slug': {
      id: '/admin/courses/$slug'
      path: '/$slug'
      fullPath: '/admin/courses/$slug'
      preLoaderRoute: typeof AdminCoursesSlugRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesSlugRoute: typeof AdminCoursesSlugRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesSlugRoute: AdminCoursesSlugRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminEventsRouteChildren {
  AdminEventsSlugRoute: typeof AdminEventsSlugRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsSlugRoute: AdminEventsSlugRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminRouteChildren {
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CoursesRoute: CoursesRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  MyRegistrationsRoute: MyRegistrationsRoute,
  SignupRoute: SignupRoute,
  TestimonialsRoute: TestimonialsRoute,
  RegisterSlugRoute: RegisterSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
